# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/podverse/02_audio.mels.ipynb.

# %% auto 0
__all__ = ['ToMel', 'cut_up', 'MelCuts', 'to_samples', 'to_ms']

# %% ../notebooks/podverse/02_audio.mels.ipynb 3
import warnings
warnings.filterwarnings("ignore")
import torch
from ..utils import cgnai_home, sliding_window_ind
from torchvision.transforms import Compose
from torchaudio.transforms import Resample, MelSpectrogram

# %% ../notebooks/podverse/02_audio.mels.ipynb 4
def ToMel(sr, wav_cut_spec:"(width, displacement)", n_mels:"features"):
    """
    Higher Order Function. Returns func that 
    maps a wav signal to its melspectrogram.
    """
    w, d = wav_cut_spec
    
    components = []
        
    components.append(MelSpectrogram(
        sample_rate = sr, 
        n_fft       = w, 
        hop_length  = d, 
        pad         = 0, 
        n_mels      = n_mels, 
        normalized  = False))

    components.append(torchaudio.transforms.AmplitudeToDB(
        stype  = 'power', 
        top_db =  80))

    to_mel = Compose(components)
    
    return to_mel

# %% ../notebooks/podverse/02_audio.mels.ipynb 5
def cut_up(x, cut_spec:"(width, displacement)"):
    """
    Cuts up an array along its last(!!!) dimension
    according to the cut spec - a tuple of 
    width and displacement.
    
    Note: The name sucks because it 
    really just is sliding windows, 
    and not "cuts" ...äaaanyway.
    """
    return x.unfold(-1, *cut_spec)

# %% ../notebooks/podverse/02_audio.mels.ipynb 6
class MelCuts():
    def __init__(self, sr, wav_cut_spec:"(width, displacement)", mel_cut_spec:"(width, displacement)", n_mels):
        self.sr = sr
        self.wav_cut_spec = wav_cut_spec
        self.mel_cut_spec = mel_cut_spec
        self.n_mels = n_mels
        
        self.to_mel = ToMel(sr, wav_cut_spec=wav_cut_spec, n_mels=n_mels)
    
    def cut_up(self, x):
        return cut_up(x, mel_cut_spec)
    
    def __call__(self, wav):
        mel = self.to_mel(wav)
        cuts = self.cut_up(mel)
        return mel, cuts

# %% ../notebooks/podverse/02_audio.mels.ipynb 7
def to_samples(i, wav_cut_spec:"(width, displacement)", mel_cut_spec:"(width, displacement)"):
    """Mel-cut index to sample index."""
    w , d  = wav_cut_spec
    w_, d_ = mel_cut_spec
    return i*d_*d, (i*d_ + w_)*d + w
            
def to_ms(s, sr):
    """From samples at a certain rate (Hz) to ms"""
    return s/sr*1000
