# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_cli.ipynb.

# %% auto 0
__all__ = ['logger', 'log', 'CGNAI_HOME', 'cgnai_hooks', 'cgnai_init', 'cgnai_clean']

# %% ../notebooks/03_cli.ipynb 2
from pathlib import Path

from os import walk, getcwd
import subprocess
import cgnai
import sys
from . import cgnai_home
from .utils import time_stamp, run_bash

# %% ../notebooks/03_cli.ipynb 3
import logging

logger = logging.getLogger("cgnai.cli")
log = logger.info

# %% ../notebooks/03_cli.ipynb 4
CGNAI_HOME = cgnai_home()        
def cgnai_hooks(hooks_dir=CGNAI_HOME/"hooks"):
    hooks    = str(hooks_dir/"*")
    githooks = str(CGNAI_HOME/'.git'/'hooks')
    
    log("copying ./hooks to .git/hooks")
    run_bash(f"cp {hooks} {githooks};")
    run_bash(f"chmod +x {githooks}/*;")

# %% ../notebooks/03_cli.ipynb 5
def cgnai_init(hooks_dir="./hooks"):
    pass

# %% ../notebooks/03_cli.ipynb 6
def cgnai_clean():
    cmd = "git diff --name-only --cached"
    staged = run_bash(cmd)
    for f in staged:
        if f.endswith(".ipynb"):
            f = cgnai_home()/f
            run_bash(f"nbdev_clean --fname {f}") # ...{f} --clear_all")
            run_bash(f"git add {f}")
