# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_logging.ipynb.

# %% auto 0
__all__ = ['cgnai_logger']

# %% ../notebooks/00_logging.ipynb 1
import logging
import sys

def cgnai_logger(name, form='%(levelname)s %(name)s|  %(message)s', stream=sys.stdout):
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler(stream)
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter(form)
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    
    return logger
