#! /bin/bash

g=$(curl  http://localhost:4040/api/tunnels 2> /dev/null)
nbserver=$(ls -1t `jupyter --runtime-dir`/*.json | head -n 1)

url=`echo $g | jq -r .tunnels[-1].public_url`
tok=`cat $nbserver | jq -r .token`
link=$url?token=$tok

echo $link